name: "baseline_volatilities"
phase: "test"
neptune_project_name: "FinancialChallenge"
neptune_group_tags: ["test", "dl"]
checkpoints_path: "checkpoints/"
return_window: True
batch_size: 1
num_workers: 1
device: "cuda"
