name: "baseline_2"
neptune_project_name: "FinancialChallenge"
neptune_group_tags: ["test", "dl"]
phase: "test"
dataroot: "data/processed/es1dia_cln.csv"
checkpoints_path: "checkpoints/"
load_path: "checkpoints/baseline/checkpoint_latest.pt"
window: 50
window_stride: 1
return_window: True
reg_feature: "log_return"
features:
    [
        "overnight_gap",
        "log_return",
        "log_range",
        "volatility_5",
        "volatility_20",
        "vol_z",
        "days_elapsed_z",
        "dow",
    ]
masked_features: ["log_return", "log_range", "vol_z"]
shuffle: False
batch_size: 1
num_workers: 1
in_channels: 11
d_model: 256
dow_embedding_dim: 4
k: 5
s: null # will default to k (=5)
nhead: 8
t_num_layers: 3
task_type: "reg"
margin_eps: 0.0005
device: "mps"
