name: "test"
neptune_project_name: "FinancialChallenge"
neptune_group_tags: ["train", "window"]
phase: "train"
dataroot: "data/processed/es1dia_cln.csv"
checkpoints_path: "checkpoints/"
window: 50
window_stride: 25
reg_feature: "log_return"
cls_feature: "day_class"
features: [
        "overnight_gap",
        "log_return",
        "log_range",
        "volatility_5",
        "volatility_20",
        "vol_z",
        # "days_elapsed_z",
        # "dow",
    ]
masked_features: ["log_return", "log_range", "vol_z"]
shuffle: True
batch_size: 16
num_workers: 1
d_model: 128
dow_embedding_dim: 4
k: 5
s: 2 # will default to k (=5)
nhead: 2
t_num_layers: 3
task_type: "reg"
lr: 0.0001
margin_eps: 0.0005
device: "cuda"
